version: "3"
services:
  web:
    container_name: pydate_app
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    links:
      - db
  db:
    container_name: pydate_db
    image: postgres:latest
    ports:
      - 5432
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pydate_volume:/var/lib/postgresql
  volumes:
    pydate_volume: